### ISSUE TITLE
「Guide > Essentials > Computed Properties」の翻訳

### ISSUE THREAD

**Issue by jay-es** [vuejs-translations/docs-ja#10]
次のコントリビュートガイドラインを一読して、翻訳作業をお願いします。
https://github.com/vuejs-translations/docs-ja/blob/main/.github/CONTRIBUTING.md

翻訳するページ
https://vuejs.org/guide/essentials/computed.html

対象ファイル
https://github.com/vuejs-translations/docs-ja/blob/main/src/guide/essentials/computed.md

**Comment by kazupon** [comment]
https://github.com/vuejs-translations/docs-ja/issues/6#issuecomment-1050838155 のコメントから。
@mgr-kbさん、よろしくお願いします！
