### ISSUE TITLE
Tutorial 翻訳まとめ

### ISSUE THREAD

**Issue by jay-es** [vuejs-translations/docs-ja#100]
- [x] #85
  - [x] #92
  - [x] #93
  - [x] #94
  - [x] #95
  - [x] #96
  - [x] #97
  - [x] #98
  - [x] #99
  - [x] #86
  - [x] #87
  - [x] #88
  - [x] #89
  - [x] #90
  - [x] #91

**Comment by kzhrk** [comment]
@vuejs-translations/ja
https://github.com/vuejs-translations/docs-ja/issues/85 の翻訳やります！

**Comment by tutti2612** [comment]
@vuejs-translations/ja
#92 の翻訳やります！

**Comment by ttt3pu** [comment]
@vuejs-translations/ja #96 の翻訳をやりたいです！

**Comment by Robjam** [comment]
@vuejs-translations/ja
#93 の翻訳やりたいです！

**Comment by yuri-htt** [comment]
@vuejs-translations/ja
#97 の翻訳やります！

**Comment by yuma-ito-bd** [comment]
@vuejs-translations/ja
#94 の翻訳やりたいです！

**Comment by gyvm** [comment]
@vuejs-translations/ja
#90 の翻訳やります！

**Comment by hirosi1900day** [comment]
#88 の翻訳やります！

**Comment by kzhrk** [comment]
@vuejs-translations/ja
https://github.com/vuejs-translations/docs-ja/issues/95 の翻訳やります！

**Comment by kzhrk** [comment]
@vuejs-translations/ja
https://github.com/vuejs-translations/docs-ja/issues/98 の翻訳やります！

**Comment by Robjam** [comment]
@vuejs-translations/ja
引き続き #99 の翻訳やりたいとおもいます。

**Comment by ttt3pu** [comment]
@vuejs-translations/ja https://github.com/vuejs-translations/docs-ja/issues/86 の翻訳をやりたいです！

**Comment by kzhrk** [comment]
@vuejs-translations/ja
https://github.com/vuejs-translations/docs-ja/issues/87 の翻訳やります！

**Comment by mpg-kohei-tsuchiya** [comment]
@vuejs-translations/ja
https://github.com/vuejs-translations/docs-ja/issues/89 の翻訳やります！

**Comment by mpg-yuri-tayama** [comment]
@vuejs-translations/ja
#91 の翻訳やります！

**Comment by mpg-teruo-kakikubo** [comment]
@vuejs-translations/ja https://github.com/vuejs-translations/docs-ja/issues/86 の翻訳をやりたいです！

**Comment by kazupon** [comment]
チュートリアル終わったのでcloseします！ 🎉 
みなさん、翻訳ありがとうございました！ 🙇
