### ISSUE TITLE
「About > Meet the Team」の翻訳

### ISSUE THREAD

**Issue by jay-es** [vuejs-translations/docs-ja#110]
次のコントリビュートガイドラインを一読して、翻訳作業をお願いします。
https://github.com/vuejs-translations/docs-ja/blob/main/.github/CONTRIBUTING.md

翻訳するページ
https://vuejs.org/about/team.html

対象ファイル
https://github.com/vuejs-translations/docs-ja/blob/main/src/about/team.md

**Comment by gyvm** [comment]
@vuejs-translations/ja
#110 翻訳します:bow:

**Comment by jay-es** [comment]
https://github.com/vuejs-translations/docs-ja/issues/114#issuecomment-1072282174
@gyvm よろしくお願いします！:pray:

**Comment by jay-es** [comment]
@gyvm 了解です！ ご連絡ありがとうございます:pray:
