### ISSUE TITLE
その他 翻訳まとめ（Style Guide, About, Ecosystem, Sponsor）

### ISSUE THREAD

**Issue by jay-es** [vuejs-translations/docs-ja#114]
- Style Guide
  - [x] #101
  - [x] #102
  - [x] #104
  - [x] #103
  - [x] #105
- About
  - [x] #108
  - [x] #110
  - [x] #109
  - [x] #107
  - [x] #106
- Ecosystem
  - [x] #111
  - [x] #112
- Sponsor
  - [x] #113

**Comment by gyvm** [comment]
@vuejs-translations/ja
#110 翻訳します！

**Comment by nabeken5** [comment]
@vuejs-translations/ja
https://github.com/vuejs-translations/docs-ja/issues/101 翻訳します!

**Comment by u-sho** [comment]
@vuejs-translations/ja
#102 翻訳させてください！

**Comment by nabeken5** [comment]
@vuejs-translations/ja
https://github.com/vuejs-translations/docs-ja/issues/102 翻訳します!

**Comment by u-sho** [comment]
@vuejs-translations/ja
#104 翻訳したいです！

**Comment by nabeken5** [comment]
@vuejs-translations/ja
#103 翻訳したいです！

**Comment by nabeken5** [comment]
@vuejs-translations/ja
https://github.com/vuejs-translations/docs-ja/issues/104 翻訳します!

**Comment by aytdm** [comment]
@vuejs-translations/ja こんにちは。#105 翻訳します

**Comment by Amplil** [comment]
@vuejs-translations/ja
#109 翻訳します！

**Comment by kazupon** [comment]
おお、この issue の TODO すべておわりましたね！
みなさん、そしてリードしていただいた @jay-es さん、本当にありがとうございました！
