### ISSUE TITLE

        add guide to typecheck web components written with vue #2314
    

### ISSUE THREAD

**Issue by jay-es** [vuejs-translations/docs-ja#1440]
New updates on head repo.
https://github.com/vuejs/docs/commit/d0feec9492da8adad6a6786009d23c29045d7ada

**Comment by yutaroadachi** [comment]
@jay-es こちら翻訳募集中であれば翻訳したいです！

**Comment by jay-es** [comment]
@yutaroadachi 助かります！:bow:
よろしくお願いします！
