### ISSUE TITLE

        feat: add vuetoronto23 banner
    

### ISSUE THREAD

**Issue by jay-es** [vuejs-translations/docs-ja#1553]
New updates on head repo.
https://github.com/vuejs/docs/commit/eba914e68eacceab35826e4aa8d017c80ad0ab49

**Comment by jay-es** [comment]
@kazupon 念のため確認です。
こちら VueConf Toronto のバナーを追加する issue なのですが、Vue Fes Japan が終わってからの対応で問題ないでしょうか

![image](https://github.com/vuejs-translations/docs-ja/assets/46585162/e2981fae-0d1c-4525-9fac-d11dc81bdefa)

**Comment by kazupon** [comment]
@jay-es 問題ないです！

**Comment by jay-es** [comment]
#1573 で revert されるので対応不要になりました
