### ISSUE TITLE
The appearance of the sample code for 'スロットの渡し方' is broken.

### ISSUE THREAD

**Issue by Ubugeeei** [vuejs-translations/docs-ja#1690]
I haven't had time to investigate in detail, so please let me just create an issue for now.  🙏🏻 

It wasn't happening in the English version, but it was in the Japanese. (I haven't been able to check other languages.) 
It's not that the syntax is wrong, but it seems like the rendering of mustaches (`{{ }}`) is broken due to some reason. 
I think it's probably an issue with VitePress or a related package, but I haven't been able to pinpoint the exact cause.

### ja

<img width="714" alt="スクリーンショット 2023-12-10 22 45 38" src="https://github.com/vuejs-translations/docs-ja/assets/71201308/adc5a745-04a5-428b-bda8-46a94126dfca">

https://ja.vuejs.org/guide/extras/render-function.html#passing-slots

https://github.com/vuejs-translations/docs-ja/blob/1109c724a101bbf38cc2c9d615889b66e13e155d/src/guide/extras/render-function.md#L554-L566

### en

<img width="714" alt="スクリーンショット 2023-12-10 22 45 47" src="https://github.com/vuejs-translations/docs-ja/assets/71201308/f88f738f-54b1-4289-b59b-fd6fcfb3b5e8">

https://vuejs.org/guide/extras/render-function.html#passing-slots

https://github.com/vuejs/docs/blob/f9823d90971c7b17c52031eb5b9ab07112452905/src/guide/extras/render-function.md#L554-L566

**Comment by jay-es** [comment]
@Ubugeeei Fixed by resolving #1677! 🚀

![image](https://github.com/vuejs-translations/docs-ja/assets/46585162/88d3b227-fb80-4f58-ad51-af77005c2734)

**Comment by Ubugeeei** [comment]
Thank you 😭😭
