### ISSUE TITLE
「Guide > Essentials > Watchers」の翻訳

### ISSUE THREAD

**Issue by jay-es** [vuejs-translations/docs-ja#17]
次のコントリビュートガイドラインを一読して、翻訳作業をお願いします。
https://github.com/vuejs-translations/docs-ja/blob/main/.github/CONTRIBUTING.md

翻訳するページ
https://vuejs.org/guide/essentials/watchers.html

対象ファイル
https://github.com/vuejs-translations/docs-ja/blob/main/src/guide/essentials/watchers.md

**Comment by jay-es** [comment]
https://github.com/vuejs-translations/docs-ja/issues/6#issuecomment-1070848455
@kzhrk よろしくお願いします！:pray:

**Comment by jay-es** [comment]
@kzhrk こちら作業の進捗いかがでしょうか？
（https://github.com/vuejs-translations/docs-ja/issues/6#issuecomment-1117130194 にて、@okakyo さんからも翻訳希望のコメントがあったため確認です:pray:）

**Comment by kzhrk** [comment]
@jay-es 
進捗よろしくないので担当外していただいて構いません 🙇

**Comment by jay-es** [comment]
@kzhrk ありがとうございます:bow:
@okakyo ではこちらの翻訳をお願いします:pray:
