### ISSUE TITLE

        remove unnecessary booleans
    

### ISSUE THREAD

**Issue by jay-es** [vuejs-translations/docs-ja#1746]
New updates on head repo.
https://github.com/vuejs/docs/commit/904e85191aa96eae5e1e2db2d50f701ca7289c12

**Comment by jay-es** [comment]
#1753 の後（もしくは一緒）にやる

**Comment by reona5** [comment]
@jay-es 
こちら対応したいです🙋‍♂️

**Comment by jay-es** [comment]
@reona5 ありがとうございます！
よろしくお願いします！ :pray:
