### ISSUE TITLE

        add compile-time flags reference
    

### ISSUE THREAD

**Issue by jay-es** [vuejs-translations/docs-ja#1748]
New updates on head repo.
https://github.com/vuejs/docs/commit/5fd82f25efdbd40bc2ba524822975f962d82aece

**Comment by TirolJPN** [comment]
はじめまして、こちら自分の方で対応させていただけませんでしょうか？

他に対応すべき issue 等ありましたらご指摘いただけますと 🙇

**Comment by jay-es** [comment]
@TirolJPN はい、よろしくお願いします！ :pray:
