### ISSUE TITLE

        mark reactivity transform removed
    

### ISSUE THREAD

**Issue by jay-es** [vuejs-translations/docs-ja#1749]
New updates on head repo.
https://github.com/vuejs/docs/commit/60f19d358f6a4c2ec4979d5132aae6e52a402e94

**Comment by kokoakuma** [comment]
@jay-es 対応したいです！ 🙋

**Comment by jay-es** [comment]
@kokoakuma ありがとうございます！
よろしくお願いします！ 🙏
