### ISSUE TITLE

        jsxImportSource
    

### ISSUE THREAD

**Issue by jay-es** [vuejs-translations/docs-ja#1750]
New updates on head repo.
https://github.com/vuejs/docs/commit/0d6371ed8783c093543fb6f904ad1e6aad4afa0c

**Comment by yamashita-ki** [comment]
対応します！

**Comment by jay-es** [comment]
@yamashita-ki ありがとうございます！
よろしくお願いします！ :pray:

**Comment by yamashita-ki** [comment]
PR出せていただきました。
お時間のある時にご確認よろしくお願いします🙏
あけましておめでとうございます。今年もよろしくお願いします！
