### ISSUE TITLE

        computed stability optimization
    

### ISSUE THREAD

**Issue by jay-es** [vuejs-translations/docs-ja#1753]
New updates on head repo.
https://github.com/vuejs/docs/commit/5e486e4b1481024f2a343228a25e0744abf4285c

**Comment by yutaroadachi** [comment]
こちら対応したいです！

**Comment by yutaroadachi** [comment]
@jay-es こちら対応したいです！

**Comment by jay-es** [comment]
@yutaroadachi ありがとうございます 🙏
よろしくお願いします！
