### ISSUE TITLE

        use direct discord invite link
    

### ISSUE THREAD

**Issue by jay-es** [vuejs-translations/docs-ja#1887]
New updates on head repo.
https://github.com/vuejs/docs/commit/8efb4cf6271fed2cf715416d151183f9241a21e5

**Comment by taku-y-9308** [comment]
@jay-es
こちら対応してもよろしいでしょうか？ 🙏

**Comment by jay-es** [comment]
@taku-y-9308 ありがとうございます！
よろしくお願いします 🙏
