### ISSUE TITLE

        docs: link API reference for Suspense
    

### ISSUE THREAD

**Issue by jay-es** [vuejs-translations/docs-ja#1899]
New updates on head repo.
https://github.com/vuejs/docs/commit/c38056cef6cc5ad15d9cfd64c6de2100d18aae78

**Comment by taku-y-9308** [comment]
@jay-es 
こちら対応してもOKでしょうか？

**Comment by jay-es** [comment]
@taku-y-9308 ありがとうございます！
ぜひよろしくお願いします！ 🙏
