### ISSUE TITLE
「リアクティブプロキシ vs. 独自」という訳の改善 (原文: Reactive Proxy vs. Original)

### ISSUE THREAD

**Issue by kosuke222naito** [vuejs-translations/docs-ja#2141]
[リアクティブプロキシ vs. 独自](https://ja.vuejs.org/guide/essentials/reactivity-fundamentals#reactive-proxy-vs-original-1)
という訳について改善できるのではないかと考えています。
しかし、私自身のVueの知識が不十分なため相談に乗っていただきたく、PRを作成するのではなくissueを立てました。

続くコード例
```js
const raw = {}
const proxy = reactive(raw)

// プロキシはオリジナルと同じではありません。
console.log(proxy === raw) // false
```
の中で `raw` という変数が `proxy` に対して用いられていることからも、"original" は独自という意味よりも生の、元の、元々の、のような意味に近いのではないかと思います。

改善についての案ですが、コード例内のコメント行にある「オリジナル」を使って、
「リアクティブプロキシ vs. オリジナル」
とするのはいかがでしょうか？

オープンなリポジトリにissueを立てることが初めてでして、、、
間違いや失礼なことなどがあったら申し訳ございません。
ご確認よろしくお願いいたします。

**Comment by jay-es** [comment]
@kosuke222naito ご提案ありがとうございます！
確かに「独自」だと理解しづらいですね...
「オリジナル」も急に出てくると分かりづらい（本文を読んだあとに意味が分かる感じ）なので、「元のオブジェクト」にしてしまうのがよさそうですね

**Comment by kosuke222naito** [comment]
@jay-es 
確認ありがとうございます！

「元のオブジェクト」に直すPR出そうと思います🙇‍♂️
よろしくお願いします。
