### ISSUE TITLE
「Guide > Components In-Depth > Component Events」の翻訳

### ISSUE THREAD

**Issue by jay-es** [vuejs-translations/docs-ja#22]
次のコントリビュートガイドラインを一読して、翻訳作業をお願いします。
https://github.com/vuejs-translations/docs-ja/blob/main/.github/CONTRIBUTING.md

翻訳するページ
https://vuejs.org/guide/components/events.html

対象ファイル
https://github.com/vuejs-translations/docs-ja/blob/main/src/guide/components/events.md

**Comment by kazupon** [comment]
@bobstrange 
https://github.com/vuejs-translations/docs-ja/issues/6#issuecomment-1175135724
よろしくお願いします！

**Comment by jay-es** [comment]
@bobstrange 
8256557b877c670593b45f6b36b3eb9b164030e5 と c69ac26ebe1a18051976e8f5a354c43a59d74331 でファイルに変更が入っているので、最新の main を取り込んで作業をお願いします:pray:

**Comment by jay-es** [comment]
@bobstrange さらに変更が入っているので対応よろしくお願いします:pray:
https://github.com/vuejs-translations/docs-ja/pull/775/files#diff-ac8639c8fbe4683fefc37e150917c47b2bcd99de6ae2c85e1628324be8f5d314

**Comment by bobstrange** [comment]
@kazupon @jay-es 

こちら対応が遅くなりましてすみません :bow:
引き続き対応させていただければと思います。
よろしくお願いします :bow:

**Comment by kazupon** [comment]
@bobstrange 
ありがとうございます！
本当にやるのが難しいようでしたら、言ってくださいね！ 😉 
無理して負担になってしまうのも精神的によくありませんので。

**Comment by kazupon** [comment]
@bobstrange 
翻訳お願いしているところ、すいません。
こちらの翻訳ですが、こちらで巻き取っても大丈夫でしょうか。:pray:

GitHub Discussion の[ここ](https://github.com/vuejs-translations/docs-ja/discussions/464#discussioncomment-3041310) にもあるとおり、guid eの部分が終わったら公開したいと思っておりまして、残りがこちらの部分になっております。
他の API などの部分はまだ翻訳途中ですが、guide だけでもすべて日本語翻訳された状態で公開されることで、日本のコミュニティにみみなさんに助けになると思っています。

**Comment by jay-es** [comment]
ある程度進んでいれば先行で公開してもよいかなと思いましたが、そうでもないとのことなので自分の方で翻訳させていただきます:pray:

**Comment by kazupon** [comment]
@bobstrange 
譲っていただきありがとうございます！進めさせていただきます。

@jay-es 
ありがとうございます！よろしくお願いします。
