### ISSUE TITLE

        Added a link explaining how to use inheritAttrs in normal <script> (#…
    

### ISSUE THREAD

**Issue by jay-es** [vuejs-translations/docs-ja#2236]
New updates on head repo.
https://github.com/vuejs/docs/commit/9a4c8127181cc411e1a330d692b6d7c457f06db1

**Comment by splendente** [comment]
@jay-es 
対応したいです！

**Comment by jay-es** [comment]
@splendente ありがとうございます！
よろしくお願いします 🙏
