### ISSUE TITLE

        remove version badages for previous minors
    

### ISSUE THREAD

**Issue by jay-es** [vuejs-translations/docs-ja#2254]
New updates on head repo.
https://github.com/vuejs/docs/commit/b6339b62a9522eb195a24ef74ee6392d65d2bfd7

**Comment by jay-es** [comment]
#2256 の後に対応

**Comment by jay-es** [comment]
src/api/composition-api-helpers.md は #2278 にて対応済み

**Comment by tkworks1214** [comment]
@jay-es 
対応したいです！ 🙏

**Comment by jay-es** [comment]
@tkworks1214 ありがとうございます！
よろしくお願いします！ 🙏
