### ISSUE TITLE

        3.5: useTemplateRef()
    

### ISSUE THREAD

**Issue by jay-es** [vuejs-translations/docs-ja#2256]
New updates on head repo.
https://github.com/vuejs/docs/commit/71cec8136523d000641c7f502b3b9e57cd143d79

**Comment by jay-es** [comment]
https://github.com/vuejs-translations/docs-ja/pull/2278 にて対応済み

**Comment by jay-es** [comment]
以下が未対応だった
- src/guide/essentials/template-refs.md
- src/guide/typescript/composition-api.md

**Comment by jay-es** [comment]
#2286 も一緒にお願いします

**Comment by NaokiHaba** [comment]
@jay-es 
対応したいです！

**Comment by NaokiHaba** [comment]
- [ ] src/guide/essentials/template-refs.md
- [ ] src/guide/typescript/composition-api.md
- [ ] #2286
