### ISSUE TITLE

        3.5: data-allow-mismatch
    

### ISSUE THREAD

**Issue by jay-es** [vuejs-translations/docs-ja#2259]
New updates on head repo.
https://github.com/vuejs/docs/commit/9bc11b23fbaa0a4f8af7c9e9c3f50f588d30f434

**Comment by tkworks1214** [comment]
@jay-es 
こちらの翻訳対応させていただきたいです 🙏

**Comment by jay-es** [comment]
@tkworks1214 ありがとうございます！
よろしくお願いします！ 🙏
