### ISSUE TITLE

        3.5: useId and app.config.idPrefix
    

### ISSUE THREAD

**Issue by jay-es** [vuejs-translations/docs-ja#2261]
New updates on head repo.
https://github.com/vuejs/docs/commit/b9ed0eb0b7c4a82ea2e50408d2d664151530d03b

**Comment by Limxxx** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by jay-es** [comment]
@yamanoku 助かります！
よろしくお願いします :pray:

**Comment by jay-es** [comment]
@yamanoku すみません、後続のコミットで一箇所訂正されていることに気づきました。
L622 のコロンはなしでお願いします :pray:
https://github.com/vuejs/docs/commit/3c4ecd8c40a3a980667ccdac6df44e81c4217738#diff-83f8ade21b3a78893350f4def2563b27501d6e926948e23f4a1cc2c7f908562dR634

**Comment by yamanoku** [comment]
https://github.com/vuejs/docs/commit/e3d9fc60f6b2c92f0d3f2348c0025fabf580364d#diff-221b6c26fbf90f7880383444a1b8ff16a451adcbcd0a8e1ee11eb4d21dfada05 で新規ページ作成されてuseIdが移動してるっぽい :eyes:

**Comment by jay-es** [comment]
@yamanoku すみません、この issue #2258 がそれですね...（ファイル名のみで後続タスク判定しましたが差分まで確認していなかった...）
もしよければ両方対応いただいてもよろしいでしょうか 🙇‍♂️

**Comment by yamanoku** [comment]
@jay-es 了解です！そちら対応します！
