### ISSUE TITLE

        docs: remarks about minor versions
    

### ISSUE THREAD

**Issue by jay-es** [vuejs-translations/docs-ja#2270]
New updates on head repo.
https://github.com/vuejs/docs/commit/7f5558934b13e824a1a571377a72b5f07fcd31d5

**Comment by jay-es** [comment]
#2254 の後に対応

**Comment by tkworks1214** [comment]
@jay-es 
こちら対応したいです！

**Comment by jay-es** [comment]
@tkworks1214 助かります！
よろしくお願いします！ :pray:
