### ISSUE TITLE

        docs: add omitted anchors for 3.5
    

### ISSUE THREAD

**Issue by jay-es** [vuejs-translations/docs-ja#2298]
New updates on head repo.
https://github.com/vuejs/docs/commit/1128a40b4a4e1d61be39311166ea9e65ab85344f

**Comment by NaokiHaba** [comment]
@jay-es 
対応したいです🙇

**Comment by jay-es** [comment]
@NaokiHaba ありがとうございます！
よろしくお願いします！ 🙇
