### ISSUE TITLE
        docs: fix issue with autofocus on custom directives page

### ISSUE THREAD

**Issue by jay-es** [vuejs-translations/docs-ja#2305]
New updates on head repo.
https://github.com/vuejs/docs/commit/ac7a921f0124c62b993fa2059e7a21db6877f9de

**Comment by NaokiHaba** [comment]
@jay-es 
対応します！

**Comment by jay-es** [comment]
@NaokiHaba 助かります！
よろしくお願いします！ 🙏

**Comment by NaokiHaba** [comment]
@jay-es 
確認したところ、変更箇所が同じファイルのようなので https://github.com/vuejs-translations/docs-ja/issues/2325 もまとめて対応しましょうか？

**Comment by jay-es** [comment]
@NaokiHaba すみません、コメント見落としていました。
関連する内容なのでまとめて対応しちゃってください！ :pray:
