### ISSUE TITLE

        doc(fix vuejs/core#11367):add a warn about '~' in src-imports
    

### ISSUE THREAD

**Issue by jay-es** [vuejs-translations/docs-ja#2374]
New updates on head repo.
https://github.com/vuejs/docs/commit/78d61f2dae1858153e35e0bc93052387c88d7a19

**Comment by splendente** [comment]
@jay-es 
対応したいです！

**Comment by jay-es** [comment]
@splendente ぜひよろしくお願いします！ 🙏
