### ISSUE TITLE

        Update useId link
    

### ISSUE THREAD

**Issue by jay-es** [vuejs-translations/docs-ja#2378]
New updates on head repo.
https://github.com/vuejs/docs/commit/2d1235ba12e473422ab75ee8f1e381308fdd27ee

**Comment by splendente** [comment]
@jay-es 
対応したいです！

**Comment by splendente** [comment]
すみません、対応するといった後で恥ずかしいのですが、既に日本語ドキュメントではリンク先が修正後と同じになっていたため、対応不要だと思います。
https://github.com/vuejs-translations/docs-ja/blob/5e775bdaf207d14cb099e42822783b56ddf816b1/src/api/application.md?plain=1#L630

**Comment by jay-es** [comment]
@splendente たしかにすでに正しいパスになっていますね。
このままクローズします。
ご確認ありがとうございます！ 🙏
