### ISSUE TITLE
「Guide > Components In-Depth > Slots」の翻訳

### ISSUE THREAD

**Issue by jay-es** [vuejs-translations/docs-ja#24]
次のコントリビュートガイドラインを一読して、翻訳作業をお願いします。
https://github.com/vuejs-translations/docs-ja/blob/main/.github/CONTRIBUTING.md

翻訳するページ
https://vuejs.org/guide/components/slots.html

対象ファイル
https://github.com/vuejs-translations/docs-ja/blob/main/src/guide/components/slots.md

**Comment by jay-es** [comment]
https://github.com/vuejs-translations/docs-ja/issues/6#issuecomment-1129526852
@shuuji3 よろしくお願いします！

**Comment by jay-es** [comment]
@shuuji3 ファイルに変更が入っているので、対応よろしくお願いします:pray:
https://github.com/vuejs-translations/docs-ja/pull/775/files#diff-1f758009e7e144536017678fb7703c7443e762a4cec3d7bdc7a1c575387ab61b

**Comment by shuuji3** [comment]
@jay-es ご連絡ありがとうございます！ 最新の状態に合わせて更新します。

途中まで翻訳していたのですが、長期間止まってしまっていてすみません。早めに仕上げます。

**Comment by shuuji3** [comment]
とりあえずdraft PRだけ作りました 🙏🏻

**Comment by shuuji3** [comment]
翻訳が終わりました。レビューよろしくお願いします
