### ISSUE TITLE
「Guide > Components In-Depth > Provide / Inject」の翻訳

### ISSUE THREAD

**Issue by jay-es** [vuejs-translations/docs-ja#25]
次のコントリビュートガイドラインを一読して、翻訳作業をお願いします。
https://github.com/vuejs-translations/docs-ja/blob/main/.github/CONTRIBUTING.md

翻訳するページ
https://vuejs.org/guide/components/provide-inject.html

対象ファイル
https://github.com/vuejs-translations/docs-ja/blob/main/src/guide/components/provide-inject.md

**Comment by kazupon** [comment]
@hiro-lapis
https://github.com/vuejs-translations/docs-ja/issues/6#issuecomment-1103623465 より、
よろしくお願いします。
