### ISSUE TITLE
「Guide > Reusability > Custom Directives」の翻訳

### ISSUE THREAD

**Issue by jay-es** [vuejs-translations/docs-ja#28]
次のコントリビュートガイドラインを一読して、翻訳作業をお願いします。
https://github.com/vuejs-translations/docs-ja/blob/main/.github/CONTRIBUTING.md

翻訳するページ
https://vuejs.org/guide/reusability/custom-directives.html

対象ファイル
https://github.com/vuejs-translations/docs-ja/blob/main/src/guide/reusability/custom-directives.md

**Comment by kazupon** [comment]
@hiro-lapis 
こちらお願いします！
https://github.com/vuejs-translations/docs-ja/issues/6#issuecomment-1181299871
