### ISSUE TITLE
「Guide > Scaling Up > Single-File Components」の翻訳

### ISSUE THREAD

**Issue by jay-es** [vuejs-translations/docs-ja#35]
次のコントリビュートガイドラインを一読して、翻訳作業をお願いします。
https://github.com/vuejs-translations/docs-ja/blob/main/.github/CONTRIBUTING.md

翻訳するページ
https://vuejs.org/guide/scaling-up/sfc.html

対象ファイル
https://github.com/vuejs-translations/docs-ja/blob/main/src/guide/scaling-up/sfc.md

**Comment by naokie** [comment]
https://github.com/vuejs-translations/docs-ja/issues/6#issuecomment-1072607530
@komura-c さん、よろしくお願いします！
