### ISSUE TITLE
「Guide > Getting Started > Introduction」の翻訳

### ISSUE THREAD

**Issue by jay-es** [vuejs-translations/docs-ja#4]
次のコントリビュートガイドラインを一読して、翻訳作業をお願いします。
https://github.com/vuejs-translations/docs-ja/blob/main/.github/CONTRIBUTING.md

翻訳するページ
https://vuejs.org/guide/introduction.html

対象ファイル
https://github.com/vuejs-translations/docs-ja/blob/main/src/guide/introduction.md

**Comment by tanquar** [comment]
翻訳やります！

**Comment by jay-es** [comment]
@tanquar ただいま準備中です。
募集開始したら vue.js-jp の Slack や Twitter でアナウンスがあると思いますのでしばらくお待ち下さい:pray:

**Comment by tanquar** [comment]
それは失礼しました、取り消しました。発表を待ちます。

**Comment by kazupon** [comment]
こちら、翻訳開始しても大丈夫です！
https://twitter.com/vuefes/status/1497009445317926914

**Comment by jay-es** [comment]
https://github.com/vuejs-translations/docs-ja/issues/6#issuecomment-1051671803
@tanquar よろしくお願いします:pray:
