### ISSUE TITLE
「Guide > Best Practices > Performance」の翻訳

### ISSUE THREAD

**Issue by jay-es** [vuejs-translations/docs-ja#42]
次のコントリビュートガイドラインを一読して、翻訳作業をお願いします。
https://github.com/vuejs-translations/docs-ja/blob/main/.github/CONTRIBUTING.md

翻訳するページ
https://vuejs.org/guide/best-practices/performance.html

対象ファイル
https://github.com/vuejs-translations/docs-ja/blob/main/src/guide/best-practices/performance.md

**Comment by kazupon** [comment]
https://github.com/vuejs-translations/docs-ja/issues/6#issuecomment-1050817836 コメントから。
@takmatsukawa さん、よろしくお願いします。
