### ISSUE TITLE
「Guide > Best Practices > Security」の翻訳

### ISSUE THREAD

**Issue by jay-es** [vuejs-translations/docs-ja#44]
次のコントリビュートガイドラインを一読して、翻訳作業をお願いします。
https://github.com/vuejs-translations/docs-ja/blob/main/.github/CONTRIBUTING.md

翻訳するページ
https://vuejs.org/guide/best-practices/security.html

対象ファイル
https://github.com/vuejs-translations/docs-ja/blob/main/src/guide/best-practices/security.md

**Comment by kazupon** [comment]
@hiro-lapis
https://github.com/vuejs-translations/docs-ja/issues/6#issuecomment-1108748700 より
よろしくお願いします！
