### ISSUE TITLE
「Guide > TypeScript > Using Vue with TypeScript」の翻訳

### ISSUE THREAD

**Issue by jay-es** [vuejs-translations/docs-ja#45]
次のコントリビュートガイドラインを一読して、翻訳作業をお願いします。
https://github.com/vuejs-translations/docs-ja/blob/main/.github/CONTRIBUTING.md

翻訳するページ
https://vuejs.org/guide/typescript/overview.html

対象ファイル
https://github.com/vuejs-translations/docs-ja/blob/main/src/guide/typescript/overview.md

**Comment by kazupon** [comment]
https://github.com/vuejs-translations/docs-ja/issues/6#issuecomment-1050824584 のコメントから。
@ryoheinan さん、よろしくお願いします！
