### ISSUE TITLE
「Guide > TypeScript > TypeScript with Composition API」の翻訳

### ISSUE THREAD

**Issue by jay-es** [vuejs-translations/docs-ja#46]
次のコントリビュートガイドラインを一読して、翻訳作業をお願いします。
https://github.com/vuejs-translations/docs-ja/blob/main/.github/CONTRIBUTING.md

翻訳するページ
https://vuejs.org/guide/typescript/composition-api.html

対象ファイル
https://github.com/vuejs-translations/docs-ja/blob/main/src/guide/typescript/composition-api.md

**Comment by kazupon** [comment]
https://github.com/vuejs-translations/docs-ja/issues/6#issuecomment-1050941259 のコメントから。
@bobstrange さん、よろしくお願いします！
