### ISSUE TITLE
「Guide > Getting Started > Quick Start」の翻訳

### ISSUE THREAD

**Issue by jay-es** [vuejs-translations/docs-ja#5]
次のコントリビュートガイドラインを一読して、翻訳作業をお願いします。
https://github.com/vuejs-translations/docs-ja/blob/main/.github/CONTRIBUTING.md

翻訳するページ
https://vuejs.org/guide/quick-start.html

対象ファイル
https://github.com/vuejs-translations/docs-ja/blob/main/src/guide/quick-start.md

**Comment by u-sho** [comment]
こちら翻訳したいです！
