### ISSUE TITLE
「Guide > Extra Topics > Reactivity in Depth」の翻訳

### ISSUE THREAD

**Issue by jay-es** [vuejs-translations/docs-ja#50]
次のコントリビュートガイドラインを一読して、翻訳作業をお願いします。
https://github.com/vuejs-translations/docs-ja/blob/main/.github/CONTRIBUTING.md

翻訳するページ
https://vuejs.org/guide/extras/reactivity-in-depth.html

対象ファイル
https://github.com/vuejs-translations/docs-ja/blob/main/src/guide/extras/reactivity-in-depth.md

**Comment by kazupon** [comment]
https://github.com/vuejs-translations/docs-ja/issues/6#issuecomment-1142254640
@hiro-lapis 
よろしくお願いします！
