### ISSUE TITLE
「Guide > Extra Topics > Rendering Mechanism」の翻訳

### ISSUE THREAD

**Issue by jay-es** [vuejs-translations/docs-ja#51]
次のコントリビュートガイドラインを一読して、翻訳作業をお願いします。
https://github.com/vuejs-translations/docs-ja/blob/main/.github/CONTRIBUTING.md

翻訳するページ
https://vuejs.org/guide/extras/rendering-mechanism.html

対象ファイル
https://github.com/vuejs-translations/docs-ja/blob/main/src/guide/extras/rendering-mechanism.md

**Comment by kazupon** [comment]
@hiro-lapis 
https://github.com/vuejs-translations/docs-ja/issues/6#issuecomment-1168045546
こちらお願いします！
