### ISSUE TITLE
「Guide > Extra Topics > Render Functions & JSX」の翻訳

### ISSUE THREAD

**Issue by jay-es** [vuejs-translations/docs-ja#52]
次のコントリビュートガイドラインを一読して、翻訳作業をお願いします。
https://github.com/vuejs-translations/docs-ja/blob/main/.github/CONTRIBUTING.md

翻訳するページ
https://vuejs.org/guide/extras/render-function.html

対象ファイル
https://github.com/vuejs-translations/docs-ja/blob/main/src/guide/extras/render-function.md

**Comment by kazupon** [comment]
@KanDai 
https://github.com/vuejs-translations/docs-ja/issues/6#issuecomment-1173672093
よろしくお願いします！

**Comment by jay-es** [comment]
@KanDai ファイルに変更が入っているので、対応よろしくお願いします:pray:
https://github.com/vuejs-translations/docs-ja/pull/775/files#diff-1a94ee8cdadf36f62aac3f31b4d1b6fae9ec3255658a23c2117a5262a5ed79d8

**Comment by KanDai** [comment]
@jay-es 
かしこまりました！ありがとうございます！

翻訳作業が遅くなっていてすみません。来週前半には一旦完了できる予定です。
