### ISSUE TITLE
「Guide > Extra Topics > Animation Techniques」の翻訳

### ISSUE THREAD

**Issue by jay-es** [vuejs-translations/docs-ja#54]
次のコントリビュートガイドラインを一読して、翻訳作業をお願いします。
https://github.com/vuejs-translations/docs-ja/blob/main/.github/CONTRIBUTING.md

翻訳するページ
https://vuejs.org/guide/extras/animation.html

対象ファイル
https://github.com/vuejs-translations/docs-ja/blob/main/src/guide/extras/animation.md

**Comment by kazupon** [comment]
from https://github.com/vuejs-translations/docs-ja/issues/6#issuecomment-1141566457
@KanDai 
よろしくお願いします！

**Comment by KanDai** [comment]
すみません、時間が取れず作業できていないのですが今週やります！
