### ISSUE TITLE
Guide 翻訳まとめ (total: 51 markdown files)

### ISSUE THREAD

**Issue by jay-es** [vuejs-translations/docs-ja#6]
- Getting Started
  - [x] #4
  - [x] #5
- Essentials
  - [x] #7
  - [x] #8
  - [x] #9
  - [x] #10
  - [x] #11
  - [x] #12
  - [x] #13
  - [x] #14
  - [x] #15
  - [x] #16
  - [x] #17
  - [x] #18
  - [x] #19
- Components In-Depth
  - [x] #20
  - [x] #21
  - [x] #22
  - [x] #23
  - [x] #24
  - [x] #25
  - [x] #26
- Reusability
  - [x] #27
  - [x] #28
  - [x] #29
- Built-in Components
  - [x] #30
  - [x] #31
  - [x] #32
  - [x] #33
  - [x] #34
- Scaling Up
  - [x] #35
  - [x] #36
  - [x] #37
  - [x] #38
  - [x] #39
  - [x] #40
- Best Practices
  - [x] #41
  - [x] #42
  - [x] #43
  - [x] #44
- TypeScript
  - [x] #45
  - [x] #46
  - [x] #47
- Extra Topics
  - [x] #48
  - [x] #49
  - [x] #50
  - [x] #51
  - [x] #52
  - [x] #53
  - [x] #54
  - [x] #55

total: 51 markdown files

**Comment by takmatsukawa** [comment]
#42 の翻訳やりたいです @vuejs-translations/ja

**Comment by ryoheinan** [comment]
@vuejs-translations/ja
#45 の翻訳をやりたいです！

**Comment by mgr-kb** [comment]
@vuejs-translations/ja
https://github.com/vuejs-translations/docs-ja/issues/10 の翻訳をやりたいです！

**Comment by bobstrange** [comment]
https://github.com/vuejs-translations/docs-ja/issues/46 の翻訳やりたいです @vuejs-translations/ja

**Comment by kazupon** [comment]
@takmatsukawa 
ありがとうございます！
#42 お願いします！

**Comment by u-sho** [comment]
@vuejs-translations/ja
#5 の翻訳をしたいです！

**Comment by t0yohei** [comment]
@vuejs-translations/ja
https://github.com/vuejs-translations/docs-ja/issues/12 の翻訳をしたいです！

**Comment by tanquar** [comment]
#4 の翻訳をやりたいです！

**Comment by kohbis** [comment]
@vuejs-translations/ja
#16 の翻訳をやりたいです。

**Comment by okakyo** [comment]
@vuejs-transitions/ja
https://github.com/vuejs-translations/docs-ja/issues/14 の翻訳がしたいです。

**Comment by yamanoku** [comment]
@vuejs-translations/ja
https://github.com/vuejs-translations/docs-ja/issues/53 翻訳担当したいです

**Comment by t0yohei** [comment]
@vuejs-translations/ja
https://github.com/vuejs-translations/docs-ja/issues/41 の翻訳をしたいです！

**Comment by tanquar** [comment]
@vuejs-translations/ja
#8 の翻訳やります！

**Comment by kzhrk** [comment]
@vuejs-translations/ja
https://github.com/vuejs-translations/docs-ja/issues/17 の翻訳やります！

**Comment by yamanoku** [comment]
@vuejs-translations/ja
https://github.com/vuejs-translations/docs-ja/issues/33 翻訳担当したいです

**Comment by komura-c** [comment]
@vuejs-translations/ja
#35 の翻訳やりたいです

**Comment by takmatsukawa** [comment]
@vuejs-translations/ja #43 の翻訳やります

**Comment by bobstrange** [comment]
@vuejs-translations/ja
#47 の翻訳やりたいです

**Comment by hiro-lapis** [comment]
@vuejs-translations/ja
#49 翻訳やりたいです

**Comment by kohbis** [comment]
@vuejs-translations/ja
https://github.com/vuejs-translations/docs-ja/issues/15 の翻訳をやりたいです。

**Comment by hiro-lapis** [comment]
@vuejs-translations/ja
https://github.com/vuejs-translations/docs-ja/issues/23 の翻訳をやりたいです

**Comment by tanquar** [comment]
@vuejs-translations/ja
#13 の翻訳やります！

**Comment by bobstrange** [comment]
@vuejs-translations/ja
#34 の翻訳やりたいです

**Comment by hiro-lapis** [comment]
@vuejs-translations/ja
#19 の翻訳させてもらってもいいでしょうか

**Comment by tanquar** [comment]
@vuejs-translations/ja
#18 の翻訳やります！

**Comment by bobstrange** [comment]
@vuejs-translations/ja

#30 の翻訳やりたいです

**Comment by hiro-lapis** [comment]
@vuejs-translations/ja

#25 の翻訳させてもらってもいいですか

**Comment by tanquar** [comment]
@vuejs-translations/ja
#20 の翻訳やります！

**Comment by hiro-lapis** [comment]
@vuejs-translations/ja
#40 の翻訳させてもらってもいいですか

**Comment by tanquar** [comment]
@vuejs-translations/ja
#21 の翻訳やります！

**Comment by shuuji3** [comment]
@vuejs-translations/ja
こんにちは🙂
#26 の翻訳をしたいです。

(ちょっと気になったのですが、`@vuejs-translations/ja` は正しくリンクになっていないようです。メンション先はこれであっていますか？)

**Comment by kazupon** [comment]
@shuuji3 
> (ちょっと気になったのですが、`@vuejs-translations/ja` は正しくリンクになっていないようです。メンション先はこれであっていますか？)

気苦労させてしません。
リンクはされていませんが、メンション(通知)は来ていますので大丈夫です！
翻訳アサインしたのでよろしくお願いします。

**Comment by okakyo** [comment]
@vuejs-translations/ja
#17 の翻訳を行います！

**Comment by shuuji3** [comment]
@vuejs-translations/ja
次は #32 の翻訳をします。

**Comment by hiro-lapis** [comment]
@vuejs-translations/ja
#39 の翻訳をしたいです！

**Comment by bobstrange** [comment]
@vuejs-translations/ja
#31 の翻訳をやりたいです。

**Comment by KanDai** [comment]
@vuejs-translations/ja
#48 の翻訳をやりたいです！

**Comment by shuuji3** [comment]
@vuejs-translations/ja
#24 の翻訳をします！

**Comment by bobstrange** [comment]
@vuejs-translations/ja

#36 の翻訳をやりたいです。

**Comment by KanDai** [comment]
@vuejs-translations/ja
#54 の翻訳をやりたいです！

**Comment by bobstrange** [comment]
@vuejs-translations/ja
#37 の翻訳をやりたいです。

**Comment by hiro-lapis** [comment]
@vuejs-translations/ja
https://github.com/vuejs-translations/docs-ja/issues/51 の翻訳をやりたいです！

**Comment by KanDai** [comment]
@vuejs-translations/ja
#52 の翻訳をやりたいです！

**Comment by bobstrange** [comment]
@vuejs-translations/ja
#22 の翻訳をやりたいです。

**Comment by hiro-lapis** [comment]
#28 の翻訳をやりたいです🙌

**Comment by kazupon** [comment]
Guidの翻訳終わっていたのでclose します！ みなさん、翻訳ありがとうございました！
