### ISSUE TITLE
「API > Advanced APIs > Server-Side Rendering API」の翻訳

### ISSUE THREAD

**Issue by jay-es** [vuejs-translations/docs-ja#81]
次のコントリビュートガイドラインを一読して、翻訳作業をお願いします。
https://github.com/vuejs-translations/docs-ja/blob/main/.github/CONTRIBUTING.md

翻訳するページ
https://vuejs.org/api/ssr.html

対象ファイル
https://github.com/vuejs-translations/docs-ja/blob/main/src/api/ssr.md

**Comment by jay-es** [comment]
https://github.com/vuejs-translations/docs-ja/issues/84#issuecomment-1088911442
@AkrMcmr よろしくお願いします！

**Comment by jay-es** [comment]
@AkrMcmr こちら進捗いかがでしょうか？

**Comment by jay-es** [comment]
@kazupon こちら kazupon さんがアサインされていますが、翻訳進行中でしょうか？

**Comment by kazupon** [comment]
@jay-es 
あ、すいません。全然手をつけてないです。こちらお願いしていいですか？ 🙏

**Comment by jay-es** [comment]
@kazupon 了解です！:+1:
