### ISSUE TITLE
API 翻訳まとめ (total: 25 markdown files)

### ISSUE THREAD

**Issue by jay-es** [vuejs-translations/docs-ja#84]
- Global API
  - [x] #59
  - [x] #60
- Composition API
  - [x] #61
  - [x] #62
  - [x] #63
  - [x] #64
  - [x] #65
  - [x] #66
- Options API
  - [x] #67
  - [x] #68
  - [x] #69
  - [x] #70
  - [x] #71
  - [x] #72
- Built-ins
  - [x] #73
  - [x] #74
  - [x] #75
  - [x] #76
- Single File Component
  - [x] #77
  - [x] #78
  - [x] #79
- Advanced APIs
  - [x] #80
  - [x] #81
  - [x] #82
  - [x] #83

total: 25 markdown files

**Comment by shiyuu33** [comment]
@vuejs-translations/ja
#61 の翻訳やります!

**Comment by shiyuu33** [comment]
@vuejs-translations/ja
#62 の翻訳やります!

**Comment by mpg-teruo-kakikubo** [comment]
@vuejs-traslations/ja
#82 の翻訳やります!

**Comment by syusn0227** [comment]
@vuejs-traslations/ja
#59 の翻訳やります！

**Comment by jay-es** [comment]
こちらも全て翻訳完了しました。
ご協力いただいた方々ありがとうございました:tada:
