### ISSUE TITLE
「Tutorial > Props」の翻訳

### ISSUE THREAD

**Issue by jay-es** [vuejs-translations/docs-ja#88]
次のコントリビュートガイドラインを一読して、翻訳作業をお願いします。
https://github.com/vuejs-translations/docs-ja/blob/main/.github/CONTRIBUTING.md

翻訳するページ
https://vuejs.org/tutorial/#step-12

対象ファイル
https://github.com/vuejs-translations/docs-ja/blob/main/src/tutorial/src/step-12/description.md

**Comment by hirosi1900day** [comment]
こちらやります！

**Comment by jay-es** [comment]
https://github.com/vuejs-translations/docs-ja/issues/100#issuecomment-1059065951
@hirosi1900day よろしくお願いします！:pray:
