### ISSUE TITLE
「Guide > Essentials > Reactivity Fundamentals」の翻訳

### ISSUE THREAD

**Issue by jay-es** [vuejs-translations/docs-ja#9]
次のコントリビュートガイドラインを一読して、翻訳作業をお願いします。
https://github.com/vuejs-translations/docs-ja/blob/main/.github/CONTRIBUTING.md

翻訳するページ
https://vuejs.org/guide/essentials/reactivity-fundamentals.html

対象ファイル
https://github.com/vuejs-translations/docs-ja/blob/main/src/guide/essentials/reactivity-fundamentals.md

**Comment by jiyuujin** [comment]
こちら、やらせてください

**Comment by jay-es** [comment]
@jiyuujin https://github.com/vuejs-translations/docs-ja/blob/main/.github/CONTRIBUTING.md の内容を再度ご確認お願いします:pray:

**Comment by jiyuujin** [comment]
@jay-es Sorry, I've corrected the branch name and commit message.

**Comment by jiyuujin** [comment]
@jay-es すみません、ブランチ名を修正いたしました
