### ISSUE TITLE
「Tutorial > Conditional Rendering」の翻訳

### ISSUE THREAD

**Issue by jay-es** [vuejs-translations/docs-ja#96]
次のコントリビュートガイドラインを一読して、翻訳作業をお願いします。
https://github.com/vuejs-translations/docs-ja/blob/main/.github/CONTRIBUTING.md

翻訳するページ
https://vuejs.org/tutorial/#step-6

対象ファイル
https://github.com/vuejs-translations/docs-ja/blob/main/src/tutorial/src/step-6/description.md

**Comment by sunecosuri** [comment]
特にconflictしてなければやってみようと思います〜 🙋

**Comment by jay-es** [comment]
https://github.com/vuejs-translations/docs-ja/issues/100#issuecomment-1059039425
@ttt3pu よろしくお願いします！:pray:
